Adding object UrlUtils and its method generate
pi6-falcon/falcon pull request #5
Opened 2021-09-12 18:24 UTC by rafaelnarbutis

This method make a sequence of chars for we to use with host domain.

Steps of the method generate:

- Generate a UUID random 
- Get its first block of the char sequence 
- Encode the char sequence
- Return a String with the encoded sequence

2021-09-12 19:30 UTC, rafaelnarbutis commented
I changed type of the base64 lib to base64Url of the Google.

The native base64 could has a problem with paths of the app, so i added a new lib of the google to resolve the problem. 

link of the lib: https://guava.dev/releases/17.0/api/docs/com/google/common/io/BaseEncoding.html

2021-09-12 19:49 UTC, rafaelnarbutis commented
I added the substring in the final process to change the length of the chars sequence.

Obs: The max length now is six chars.

2021-09-15 01:16 UTC, eopit requested changes

2021-09-15 01:16 UTC, eopit commented on src/main/kotlin/com/falcon/falcon/utils/UrlUtils.kt
> +            UUID.randomUUID().toString().split(DELIMITER)[ZERO].encodeToByteArray()).substring(ZERO, SIX)
Why we should use encodeToByteArray and then substring it?
Maybe we should try the following code?
```
fun generate() = BaseEnconding.base64URL().encode(UUID.randomUUID().toString().substringBefore("-")
```

2021-09-26 04:42 UTC, closed without merging